### PR TITLE
Make PBKDF hash field optional

### LINKED ISSUE #473: CryptKeyslotHandle::get_pbkdf() segfaults for type Argon2I/Argon2Id keyslots
1. The `CryptKeyslotHandle::get_pbkdf()` implementation initializes a `crypt_pbkdf_type` struct with `hash` set to `null`.
2. It then invokes libcrypsetup's `crypt_keyslot_get_pbkdf` function.
3. The call ends up in [`LUKS2_keyslot_pbkdf()`](https://gitlab.com/cryptsetup/cryptsetup/-/blob/master/lib/luks2/luks2_keyslot.c#L236) where the `hash` field is set conditionally. In fact, the hash field is only used with the `Pbkdf2` type, otherwise the value is left untouched.
4. The call returns (`hash` is still `null`).
5. Implementation calls `CryptPbkdfType::try_from(type_)`.
6. The `try_from` implementation attempts to construct a `String` from the null pointer by reading it. <-- **SEGFAULT**

We may want to use `Option<String>` for the field type.

(Optionally, we may also want to switch to `Option` for other parameters, too since they are only used with certain encryption types - but at least their absence doesn't cause a segfault.)

### PR DESCRIPTION
**Pull request by frankdavid**
Fixes #473

The hash field is not always populated. The library should not try to create a String instance if hash is null.

### CODE REVIEW

**Comment by jbaublitz** [comment]
@frankdavid Thanks for the contribution! I'll review this a little bit later today. Can you rebase onto the default branch in the meantime in preparation for merge?

File: src/settings.rs [hunk 1]
```diff
@@ -73,18 +68,25 @@ pub struct CryptPbkdfTypeRef<'a> {
...
 
 impl<'a> TryInto<CryptPbkdfTypeRef<'a>> for &'a CryptPbkdfType {
     type Error = LibcryptErr;
 
     fn try_into(self) -> Result<CryptPbkdfTypeRef<'a>, Self::Error> {
-        let hash_cstring = CString::new(self.hash.as_bytes()).map_err(LibcryptErr::NullError)?;
+        let hash_cstring = self
+            .hash
+            .as_ref()
+            .map(|h| CString::new(h.as_bytes()).map_err(LibcryptErr::NullError))
```
Comment (jbaublitz) [inline src/settings.rs]: I believe this can be simplified with the `to_cstring!` macro.

File: src/settings.rs [hunk 2]
```diff
@@ -36,28 +36,23 @@ pub struct CryptPbkdfType {
...
 
 impl<'a> TryFrom<&'a libcryptsetup_rs_sys::crypt_pbkdf_type> for CryptPbkdfType {
     type Error = LibcryptErr;
 
     fn try_from(v: &'a libcryptsetup_rs_sys::crypt_pbkdf_type) -> Result<Self, Self::Error> {
+        let hash = if v.hash.is_null() {
+            None
+        } else {
+            Some(from_str_ptr!(v.hash)?.to_string())
+        };
```
Comment (jbaublitz) [inline src/settings.rs]: I believe this block can be simplified with the `ptr_to_option!` macro in combination with the `from_str_ptr!` macro and transpose.

**Review by jbaublitz — CHANGES_REQUESTED** [review]
Just two code simplification requests. I believe you also mentioned that other fields may be optional. Did it turn out that we only need to wrap the hash in an `Option` because all other fields can easily represent the default?

**Comment by frankdavid** [comment]
> Did it turn out that we only need to wrap the hash in an Option because all other fields can easily represent the default?

I looked into it and the main issue is that the backing C API does not have official sentinel values. The integer fields contain 0 when the value is "empty" but I felt it's quite risky to interpret 0 as missing (what if the backing implementation starts using 0 as a non-empty value?).

With the current way, the Rust wrapper just lets the 0s through without interpreting them. In order to move to `Option<>`, we'd need to be confident that a field can only have 0 value when it's empty (and it won't change in the future). Please let me know what you think.

**Review by jbaublitz — APPROVED** [review]
I 100% agree and have generally tended toward that approach throughout the library as you can probably see. Thanks for making the revisions. I'll approve and merge.
